export const userEndpoint = {
    register: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/register`,
    verifyOTP: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/verifyOTP`,
    resendOTP: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/resendOTP`,
    loginUser: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/login`,
    addToCart: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/addToCart`,
    makePayment: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/makePayment`,
    paymentSuccess: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/paymentSuccess`,
    getCartItems: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/getCartItems`,
    clearCookie: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/clearCookie`,
    fetchCourseDetails: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/fetchCourseDetails`,
    setNewPassword: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/setNewPassword`,
    sendOtpToEmail:`${import.meta.env.VITE_API_GATEWAY_BASE_URL}/sendOtpToEmail`,
    resendOtpToEmail: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/resendOtpToEmail`,
    resetPasswordOTP: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/resetPasswordOTP`,
    updatePassword: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/updatePassword`,
    addUserReview: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/addUserReview`,
    fetchReviewsOfCourse: `${import.meta.env.VITE_API_GATEWAY_BASE_URL}/fetchReviewsOfCourse`,
    fetchPurchasedCourses:`${import.meta.env.VITE_API_GATEWAY_BASE_URL}/fetchPurchasedCourses`,
} 